language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fitzystrikesagain/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fitzystrikesagain/docker-react npm run test